version: '3.9'
services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=lista_de_contato
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - LDC
  node-ldc:
    build: 
      context: .
      dockerfile: app.dockerfile
    container_name: node-ldc
    depends_on:
      - postgres
    restart: always
    ports:
      - 3000:3000
    networks:
      - LDC
volumes:
  db:
networks:
  LDC:
    driver: bridge